using System;
using MySql.Data.MySqlClient;

namespace DBtoDBC
{
    class DB2DBC
    {
        public static uint GlobalLocalization = 0;

        public static void ExtractAll(MySqlConnection connection)
        {
            DBCExtract.achievement_criteria(connection);
            DBCExtract.achievement(connection);
            DBCExtract.areagroup(connection);
            DBCExtract.areapoi(connection);
            DBCExtract.areatable(connection);
            DBCExtract.areatrigger(connection);
            DBCExtract.auctionhouse(connection);
            DBCExtract.bankbagslotprices(connection);
            DBCExtract.bannedaddons(connection);
            DBCExtract.barbershopstyle(connection);
            DBCExtract.battlemasterlist(connection);
            DBCExtract.chartitles(connection);
            DBCExtract.chatchannels(connection);
            DBCExtract.chrclasses(connection);
            DBCExtract.chrraces(connection);
            DBCExtract.cinematicsequences(connection);
            DBCExtract.creaturedisplayinfo(connection);
            DBCExtract.creaturedisplayinfoextra(connection);
            DBCExtract.creaturefamily(connection);
            DBCExtract.creaturemodeldata(connection);
            DBCExtract.creaturespelldata(connection);
            DBCExtract.creaturetype(connection);
            DBCExtract.currencytypes(connection);
            DBCExtract.destructiblemodeldata(connection);
            DBCExtract.dungeonencounter(connection);
            DBCExtract.durabilitycosts(connection);
            DBCExtract.durabilityquality(connection);
            DBCExtract.emotes(connection);
            DBCExtract.emotestext(connection);
            DBCExtract.faction(connection);
            DBCExtract.factiontemplate(connection);
            DBCExtract.gameobjectdisplayinfo(connection);
            DBCExtract.gemproperties(connection);
            DBCExtract.glyphproperties(connection);
            DBCExtract.glyphslot(connection);
            DBCExtract.holidays(connection);
            DBCExtract.itembagfamily(connection);
            DBCExtract.itemextendedcost(connection);
            DBCExtract.itemlimitcategory(connection);
            DBCExtract.itemrandomproperties(connection);
            DBCExtract.itemrandomsuffix(connection);
            DBCExtract.itemset(connection);
            DBCExtract.lfgdungeons(connection);
            DBCExtract.light(connection);
            DBCExtract.liquidtype(connection);
            DBCExtract.mailtemplate(connection);
            DBCExtract.map(connection);
            DBCExtract.mapdifficulty(connection);
            DBCExtract.movie(connection);
            DBCExtract.overridespelldata(connection);
            DBCExtract.powerdisplay(connection);
            DBCExtract.pvpdifficulty(connection);
            DBCExtract.questfactionrew(connection);
            DBCExtract.questsort(connection);
            DBCExtract.questxp(connection);
            DBCExtract.randproppoints(connection);
            DBCExtract.scalingstatdistribution(connection);
            DBCExtract.scalingstatvalues(connection);
            DBCExtract.skilllineability(connection);
            DBCExtract.skillline(connection);
            DBCExtract.soundentries(connection);
            DBCExtract.spellcasttimes(connection);
            DBCExtract.spellcategory(connection);
            DBCExtract.spell(connection);
            DBCExtract.spelldifficulty(connection);
            DBCExtract.spellduration(connection);
            DBCExtract.spellfocusobject(connection);
            DBCExtract.spellitemenchantmentcondition(connection);
            DBCExtract.spellitemenchantment(connection);
            DBCExtract.spellradius(connection);
            DBCExtract.spellrange(connection);
            DBCExtract.spellrunecost(connection);
            DBCExtract.spellshapeshiftform(connection);
            DBCExtract.stableslotprices(connection);
            DBCExtract.summonproperties(connection);
            DBCExtract.talent(connection);
            DBCExtract.talenttab(connection);
            DBCExtract.taxinodes(connection);
            DBCExtract.taxipath(connection);
            DBCExtract.taxipathnode(connection);
            DBCExtract.teamcontributionpoints(connection);
            DBCExtract.totemcategory(connection);
            DBCExtract.transportanimation(connection);
            DBCExtract.transportrotation(connection);
            DBCExtract.vehicle(connection);
            DBCExtract.vehicleseat(connection);
            DBCExtract.wmoareatable(connection);
            DBCExtract.worldmapoverlay(connection);
            DBCExtract.worldsafelocsdbc(connection);
        }

        public static void ExtractSpells(MySqlConnection connection)
        {
            DBCExtract.spellcasttimes(connection);
            DBCExtract.spellcategory(connection);
            DBCExtract.spell(connection);
            DBCExtract.spelldifficulty(connection);
            DBCExtract.spellduration(connection);
            DBCExtract.spellfocusobject(connection);
            DBCExtract.spellitemenchantmentcondition(connection);
            DBCExtract.spellitemenchantment(connection);
            DBCExtract.spellradius(connection);
            DBCExtract.spellrange(connection);
            DBCExtract.spellrunecost(connection);
            DBCExtract.spellshapeshiftform(connection);
        }
    }
}
